- .gitignore
- docs/design/entity.md
- docs/test/README.md
- docs/test/node-add.sh
- docs/test/node-remove.sh
- src/core/model/cluster.go
- src/core/model/node.go
- src/core/model/tumblebug/firewall.go
- src/core/model/tumblebug/tvm.go
- src/core/model/vm.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- src/rest-api/router/cluster.go
- src/rest-api/router/node.go
- src/rest-api/server.go
- src/rest-api/service/cluster.go
- src/rest-api/service/node.go
- src/scripts/k8s-join.sh
- src/utils/app/ack.go
- src/utils/config/const.go
- src/utils/lang/functions.go
- 이슈 #7 
- CSP AWS, GCP로 한정
- 현재 CSP를 구분할 방법이 없어 namespace 명으로 구분하도록 하였음
- CSP별 Image, user account, Connction Info(prefix: cb-aws, cb-gcp) 하드코딩
> Implement 'Add a Node' and 'Remove a Node' API (#7)

- docs/test/env.sh
> test: Fix env.sh for zsh

- README.md
- docs/test/get.sh
- src/core/model/spider/base.go
- src/core/model/spider/connection.go
- src/core/model/spider/region.go
- src/rest-api/service/cluster.go
- src/rest-api/service/csp.go
- src/rest-api/service/node.go
- src/utils/config/const.go
- src/utils/lang/functions.go
* AWS 리전별 AMI 확대
* AWS일 경우 CB-Spider 로 부터 connection info. 에 따른 region 조회 후 AMI 선별
* 총 20 중 16개 리전 반영
* #18
> feat: Implement "AMI" by region on AWS

- .github/workflows/prow-commands.yml
prow-commands workflow 오동작 확인을 위한, 동작 조건 변경입니다.
> Change condition to execute prow-commands workflow

- src/core/model/vm.go
- src/rest-api/service/cluster.go
- src/rest-api/service/node.go
- src/scripts/bootstrap.sh
- src/scripts/k8s-init.sh
- Kilo
- multi-cloud network overlay
- https://github.com/squat/kilo
> feature: Implement multi-cloud network overlay #20

- docs/design/entity.md
- src/core/model/cluster.go
- src/core/model/node.go
- src/core/model/request.go
- src/core/model/vm.go
- src/core/service/common.go
- src/core/service/csp.go
- src/core/service/mcir.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- src/rest-api/router/cluster.go
- src/rest-api/router/node.go
- src/rest-api/service/cluster.go
- src/rest-api/service/node.go
- src/scripts/haproxy.sh
- src/scripts/k8s-init.sh
- src/scripts/ladybug-bootstrap-canal.sh
- src/scripts/ladybug-bootstrap-kilo.sh
- src/scripts/systemd-service.sh
- src/utils/app/ack.go
- src/utils/config/const.go
- src/utils/lang/functions.go
1. control-plane high availability (#34)
고가용성을 위한 control-plane high availability 구성
haproxy 를 활용한 kubernetes api-server loadbalancing
multi-CSP 지원 및 api spec 변경
2. persistent IP alias configuration (#35)
bootstrap 개선 건
노드 리부팅시 public-ip 변경에 대한 대응 작업
public-ip 의 ip alias 를 재 정의하고 kubelet 및 설치된 network cni 설정 정보를 업데이트
reboot 시 systemd 활용하여 적용
> feature: Implement control-plane HA, persistent IP alias configuration (#34, #35, #13)

- src/core/service/cluster.go
- src/core/service/node.go
- src/rest-api/router/cluster.go
- src/rest-api/router/node.go
- rest-api/service 폴더를 core/service로 이동
> refactor: move rest-api/service/* to core/service

- src/core/service/csp.go
- src/core/service/mcir.go
- src/core/service/node.go
- src/utils/config/const.go
> feat: add new CSP(azure) support

- Dockerfile
> chore: update COPY usage in Dockerfile

- src/core/model/vm.go
- kilo (https://github.com/squat/kilo) 사용법이 변경됨에 따라, kilo 사용 시 crds.yaml 적용 추가
> feat: add crd.yaml for kilo to InstallNetworkCNI

- docs/design/cluster-create.puml
- docs/design/cluster-delete.puml
- docs/design/entity.md
- docs/design/init-cloud-connection.puml
- docs/design/node-remove.puml
- docs/design/nodes-add.puml
- docs/design/objects.puml
* update design documents for v0.4.0 release (cafe mocha version)
* Issue : Update design documents for v0.4.0 release #55
> docs: update design documents for v0.4.0 release

- src/core/model/cluster.go
- src/core/model/node.go
- src/core/model/request.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- src/main.go
- src/rest-api/router/cluster.go
- src/rest-api/router/node.go
- src/utils/app/ack.go
- docs: update swagger docs (#42)
- swagger 문서 개선
> docs: update swagger docs (#42)

- src/core/service/csp.go
- feat: add support for aws osaka region
- aws 오사카 리전 지원
> feat: add support for aws osaka region

- src/core/model/tumblebug/mcis.go
- src/core/service/cluster.go
- feat: add mcis label
- cluster 생성 시 mcis.label=mcks 추가 (cb-webtool 요청)
> feat: add mcis label

- src/core/model/vm.go
- src/scripts/addons/canal/canal_v3.20.0.yaml
- src/scripts/addons/kilo/crds_v0.3.0.yaml
- src/scripts/addons/kilo/kilo-kubeadm-flannel_v0.3.0.yaml
- src/scripts/addons/kilo/kube-flannel_v0.14.0.yaml
- src/utils/config/const.go
- feat: improve installing addons(network cni) (#64)
- network cni 설치 시 yaml 파일 변경 가능성으로 인해 vm에 복사 후 설치하도록 변경
> feat: improve installing addons(network cni) (#64)

- src/core/service/node.go
- fix: add drain/delete node when addNode failed
- 2개 이상의 노드를 추가 중 오류가 발생한 경우 이미 join된 노드가 NotReady로 남아있는 현상 발생. vm 삭제 전 drain/delete node 추가
- CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.4.13)
- CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.4.11)
> fix: add drain/delete node when addNode failed

- docs/test/ns-create.sh
- docs/test/ns-delete.sh
- docs: update ns-delete/ns-create test scripts (#109)
- namespace 등록/삭제 시 기존 namespace 전체 삭제 부분 제거
- CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.4.13)
- CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.4.11)
> docs: update ns-delete/ns-create test scripts (#109)

- docs/test/cluster-create.sh
- src/core/model/cluster.go
- src/core/model/request.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- src/grpc-api/request/test/test_api.go
- src/grpc-api/server/mcar/mcar.go
- src/utils/app/ack.go
- docs: update default network cni (to canal)
- CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.4.13)
- CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.4.12)
> docs: update default network cni (to canal)

- src/docs/v0.5.0.yaml
* v0.5.0-affogate API swagger.yaml 추가
> docs: update api-docs. for v0.5.0-affogato

- docs/test/connectioninfo-create.sh
동일 CSP에 대한 connection info 생성시 add subcommand가 정상 동작하지 않아 수정합니다.
줄 끝 공백도 일괄 제거하였습니다.
> test: fix connectioninfo-create.sh <CSP> add

- src/grpc-api/cbadm/app/function.go
- src/grpc-api/cbadm/cmd/create.go
cbadm cli 사용법 개선2
- cluster, node 생성 시 parameter 받아서 하는 방법 추가.
> feat: add a inline parameters to cbadm commands(create a cluster & add nodes) 

- go.mod
- go.sum
* clean up dependencies
* go.mod
> chore: clean up dependencies

- docs/test/mcir-delete.sh
- docs/test/mcir-list.sh
- go.mod
- go.sum
- src/core/model/types.go
- src/core/service/cluster.go
- src/core/service/mcir.go
- src/core/service/node.go
- src/core/tumblebug/mcir.go
- src/core/tumblebug/mcis.go
- src/core/tumblebug/types.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- Improve NLB & modify create cluster 
- NLB생성시  vmgroupid 지정하게 변경.
- 클러스터 생성시 control-plane 일 경우 vmgroup으로 생성되게 변경.
Tested with
CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.6.8)
CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/tag/v0.6.3)
> feat : Improve NLB & modify create cluster

- docs/test/cluster-create.sh
- docs/test/node-add.sh
- src/core/app/ack.go
- src/core/app/const.go
- src/core/service/cluster.go
- src/core/service/node.go
- src/docs/docs.go
- src/docs/swagger.json
- src/docs/swagger.yaml
- src/grpc-api/server/mcar/cluster.go
- src/rest-api/router/cluster.go
- src/rest-api/router/node.go
* API 구조 변경  'create a cluster', 'add nodes' 
* ISSUE #151 
* create a cluster
```  
{
"config": {
"installMonAgent": "no",
"kubernetes": {
"version": "1.23.13",
"networkCni": "canal",
"loadbalancer": "haproxy",
"podCidr": "10.244.0.0/16",
"serviceCidr": "10.96.0.0/12",
"serviceDnsDomain": "cluster.local",
"storageclass": {
"nfs": {
"path": "/nfs/data",
"server": "163.154.154.89"
}
},
}
},
"controlPlane": [
{
"connection": "config-aws-ap-northeast-2",
"count": 3,
"spec": "t2.medium",
"rootDisk":  {
"type": "default",
"size": "default"
}
}
],
"description": "string",
"label": "string",
"name": "cluster-01",
"worker": [
{
"connection": "config-aws-ap-northeast-2",
"count": 3,
"spec": "t2.medium",
"rootDisk":  {
"type": "default",
"size": "default"
}
}
]
}
```
* add nodes
```
{
"worker": [
{ …
```
> refactor: create a cluster api request structure

- src/core/provision/provisioner.go
- src/core/service/cluster.go
- src/core/service/mcir.go
- src/core/service/node.go
- src/core/tumblebug/mcis.go
- src/core/tumblebug/types.go
- src/rest-api/router/cluster.go
- Update to lastest version spider/tumblebug
- nlb 관련 수정 및 vmGroup -> subGroup 변경
- etcd 관련 버그 수정
- vm 이름 관련 수정 (임시 수정)
Tested with
CB-Spider (https://github.com/cloud-barista/cb-spider)  #844기준
CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug) #1270기준
> Update to lastest version spider/tumblebug

- docs/test/batch-register-cloud-info.sh.example
- docs/test/connectioninfo-create.sh
- src/core/app/const.go
- src/core/model/types.go
- src/core/service/csp.go
- src/core/service/mcir.go
- feat : Add support for NHN Cloud
- nhn cloud 지원 추가
- 기본적으로 생성되는 VPC/Subnet 의 Default Network 는 테스트가 끝나도 삭제하지 말아야함 (현재 기준)
- nlb 생성되는 것 확인함
Tested with
CB-Spider (https://github.com/cloud-barista/cb-spider) #844기준
CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug) #1270기준
> feat:Add support for NHN Cloud

- src/core/service/node.go
- fix vm creation logic when adding nodes
- vm 생성시 return 객체가 vm에서 mcis로 변경되어 그에 따른 수정
Tested with
CB-Spider (https://github.com/cloud-barista/cb-spider) v0.7.0
CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug) v0.7.0
> fix:fix vm creation logic when adding nodes

- src/core/service/mcir.go
- src/core/tumblebug/mcis.go
- src/core/tumblebug/types.go
- NLB struct 타입 변경
Tested with
CB-Spider (https://github.com/cloud-barista/cb-spider) v0.7.0
CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug) v0.7.0
> feat : Improve nlb struct

- docs/design/cluster-create.puml
- docs/design/cluster-delete.puml
- docs/design/node-remove.puml
- docs/design/nodes-add.puml
> docs: Update sequence diagrams

- src/scripts/bootstrap.sh
> fix: specify cri-tools package version to 1.25.* - #171
