cloud-barista/cb-ladybug

.github/workflows/docker-publish.yml
- Enable CI powered by GitHub Actions
- Rules
- Run tests for any PRs
- Publish `master` as Docker `latest` image
- Publish `v1.2.3` tags as releases
=> Enable CI powered by GitHub Actions (docker-publish.yml)

.github/workflows/prow-commands.yml
This PR proposes a GitHub workflow for action by command-style comments (inspired by Kubernetes Prow))
Supported comments are as follows,
/assign 
/unassign
/approve 
/retitle 
/area 
/kind 
/priority 
/remove 
/lgtm 
/close 
/reopen 
/lock 
/milestone 
/hold 
/cc 
/uncc
This GitHub workflow is based on jpmcb/prow-github-actions .
https://github.com/jpmcb/prow-github-actions/blob/main/docs/commands.md
You can see a demo PR from [here](https://github.com/seokho-son/docs/pull/18) to check actions.
=> Add workflow for action by command-style comments

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/enhancement-request.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/general-question.md, .github/workflows/prow-commands.yml
This PR proposes 
- Add GitHub Issue templates
- **Fix** GitHub workflow for action by command-style comments (inspired by Kubernetes Prow))
Supported comments are as follows,
/assign
/unassign
/approve
/retitle
/area
/kind
/priority
/remove
/lgtm
/close
/reopen
/lock
/milestone
/hold
/cc
/uncc
This GitHub workflow is based on jpmcb/prow-github-actions .
https://github.com/jpmcb/prow-github-actions/blob/main/docs/commands.md
You can see a demo PR from https://github.com/seokho-son/docs/pull/18 to check actions.
=> Add Issue-template and fix prow workflow

src/core/model/node.go, src/core/model/tumblebug/spec.go, src/core/model/vm.go, src/core/service/cluster.go, src/core/service/common.go, src/core/service/csp.go, src/core/service/mcir.go, src/core/service/node.go, src/utils/app/ack.go, src/utils/lang/functions.go
- mcir name 변경
- validation check 개선
- drain node 옵션 추가
- csp useraccount 변경
- haproxy 구성시 privateip로 변경
- vm 10개 이상일 때 connection error 수정
=> refactor/fix: update MCIR naming rule/validation, update AWS's user account, use private ip for haproxy, fix connection error over 10 VMs 

src/core/service/node.go
mcis 생성 시 vm id가 변경되어 클러스터의 노드명도 변경됨에 따라, 노드 삭제 시 hostname 조회하는 부분을 모든 csp에 적용시킴
=> Remove return code from getHostName

src/core/model/tumblebug/mcis.go, src/core/service/cluster.go
- 클러스터 삭제 시, mcis terminate 실행 후 mcis delete 실행 (mcis delete 실패 시, mcis refine 후 다시 mcis delete)
- 삭제하려는 mcis가 존재하지 않을 때 해당 cluster의 meta-data 삭제
=> Add terminate, refine to delete cluster

docs/test/README.md, docs/test/batch-register-cloud-info.sh.example, docs/test/connectioninfo-create.sh, docs/test/env.sh
Related issue: #74
> 예를 들어, https://github.com/cloud-barista/cb-ladybug/tree/master/docs/test#cloud-connection-info-%EB%93%B1%EB%A1%9D 에서
> `REGION`, `ZONE` 등의 환경변수를 계속 재활용하여 사용하고 있어서
> - GCP 등록할 때, AWS 등록할 때, Azure 등록할 때 매번 업데이트 해 주어야 합니다.
> - 실행 순서에 유의해야 합니다.
> 
> 이를
> GCP 관련 env var 에는 `GCP_` 라는 prefix 를 붙이는 식으로 CSP 별로 구분하고
> 파일로 만든 다음 (예: `cloud-connection-info.env`)
> 사용자가 이 파일을 업데이트하도록 하고
> `./connectioninfo-create.sh` 파일 실행 시 `cloud-connection-info.env` 에 있는 환경변수를 읽도록 하는
> 방안이 있을 수 있습니다.
=> Improve conn-config-env-var-names

go.mod, go.sum, src/grpc-api/interceptors/authjwt/auth.go, src/grpc-api/jwt-gen/jwt_gen.go
- Replace jwt-go with currently-being-maintained ver
- As-is: https://github.com/dgrijalva/jwt-go
- To-be: https://github.com/golang-jwt/jwt
- Related CB-Tumblebug issue: https://github.com/cloud-barista/cb-tumblebug/issues/656
- Related CB-Tumblebug PR: https://github.com/cloud-barista/cb-tumblebug/pull/661
- Related Dependabot alert: https://github.com/cloud-barista/cb-ladybug/security/dependabot/go.mod/github.com%2Fdgrijalva%2Fjwt-go/open
=> Replace jwt-go with currently-being-maintained ver

src/core/model/vm.go, src/core/service/cluster.go, src/core/service/node.go, src/utils/config/const.go
- feat: add labels to kubernetes node (csp, region, zone)
- 프로비저닝 후 생성된 노드에 CSP, region, zone 레이블을 제공
- e.g.
- topology.cloud-barista.github.io/csp=gcp
- topology.kubernetes.io/region=asia-northeast3
- topology.kubernetes.io/zone=asia-northeast3-a
- 참고 : https://kubernetes.io/ko/docs/reference/labels-annotations-taints/#topologykubernetesioregion
=> feat: add labels to kubernetes node (csp, region, zone)

docs/test/conf.env, go.mod, go.sum, src/core/model/tumblebug/mcis.go, src/core/service/cluster.go, src/core/service/node.go, src/utils/lang/functions.go
- feat: add deleteMCIS/deleteVMs for createCluster/addNode failure
- 클러스터/노드 생성 실패 시 mcis/vm 삭제 로직 추가
- fix: change mcis control url
- cb-tumblebug api 변경으로 mcis terminate/refine url 변경 (**CB-Tumblebug v0.4.8 이상에서 동작**)
- fix: remove cluster name from node name
- node name 생성 규칙 변경
- <cluster_name>-<c/w>-<idx>-<random_string> -> <c/w>-<idx>-<random_string>
- CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.4.11)
- CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.4.8)
=> feat: add deleteMCIS/deleteVMs for createCluster/addNode failure

docs/test/README.md, src/core/model/tumblebug/mcis.go, src/core/service/cluster.go, src/utils/config/const.go
- feat: add mcis.systemLabel for monitoring
- mcis 생성 시 systemLabel 값 추가
- CB-Dragonfly 실행 방법 링크 추가 (for monitoring)
- CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.4.18)
- CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.4.15)
=> feat: add mcis.systemLabel for monitoring

src/core/model/types.go, src/core/provision/machine.go, src/core/provision/provisioner.go, src/core/provision/types.go, src/core/service/cluster.go, src/core/service/csp.go, src/core/service/mcir.go, src/core/service/node.go, src/core/tumblebug/mcir.go, src/scripts/bootstrap.sh
**현상**
* 멀티 VPC 를 환경에 설치되는 클러스터 생성 시 network-cni 설치 후 etcd shutdown 되는 현상 발생
* 이슈 : #123 
**원인**
* VM의 private-ip 중복으로 인한 network-cni 오동작이  원인
* VM IP 채번 방식  (Tumblebug)
* VPC 생성 요청 시 지정된 cidr-block 내에서 채번
* 채번방식 2종 - 랜덤 채번 방식은 AWS, Alibaba,  순서 채번 방식은 GCP, Azure, Tencent, IBM 
* 순서 채번 방식은 IP가 순서대로 증가 (192.168.1.2, 192.168.1.3, 192.168.1.4, .....)
* 동일한 cidr-block 로 지정된 멀티 VPC(멀티 리전 or CSP)로 클러스터를 구성할 경우 채번방식에 따라 VM들의  private-ip 중복될 가능성
**검증 및 검토**
* Canal 인 경우 해당 네트워크 오버레이의 노드 IP를 public-ip 로 detect 되도록 지정하면 문제 해결
* calico : `kubectl annotate node {{HOSTNAME}} projectcalico.org/IPv4Address=${PUBLIC_IP}`
* flannel  : `kubectl annotate node {{HOSTNAME}} flannel.alpha.coreos.com/public-ip-overwrite=${PUBLIC_IP}`
* Kilo 경우는 private-ip 중복되면 반드시 문제 발생
*  VPC 생성 시 중복되지 않는  cidr-block 지정 필요 …
=> fix: Duplicated private-ip problem on multiple VPCs

docs/test/connectioninfo-create.sh, src/core/tumblebug/mcir.go
- https://github.com/cloud-barista/cb-spider/issues/557 
http get Method 사용시 불필요한 body 구문 삭제함.
Tested with
CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.5.0)
CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.5.0)
=> fix: Delete body for http get Method

src/core/service/mcir.go, src/core/service/type.go, src/core/tumblebug/mcir.go, src/core/tumblebug/types.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/rest-api/router/mcir.go, src/rest-api/server.go
csp 별 운용 가능한 VM 스펙 조회 API 추가
- 이슈 : Implement API that provides VM specs that can be deployed and operated by CSP #127
조회 조건 
- 필수
- connection Name
- control-plane 여부 (미 입력시 worker 설정)
- 추가  (미 입력 시 control-plane여부에 따른 최소값 강제 지정 )
- cpu 최소/최대 값
- memory 최소/최대 값
=> feat:Implement 'get VM SpecList' API

src/scripts/bootstrap.sh
- fix: Insert swapoff into k8s 1.23 install script
- k8s 1.23 버전 설치시 csp: cloudit 일때 swapoff 필요
**Tested with**
- CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.5.12)
- CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.5.11)
=> fix:Insert swapoff into k8s 1.23 install script

CHANGELOG.md, README.md, docs/design/cluster-create.puml, docs/design/cluster-delete.puml, docs/design/node-remove.puml, docs/design/nodes-add.puml, go.mod, go.sum
- docs: update for v0.6.0-cafelatte release
- go.mod
- README.md
- CHANGELOG.md
- design documents
**Tested with**
- CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.5.12-p1)
- CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.5.11)
=> docs: update for v0.6.0-cafelatte release

docs/design/entity.md, src/core/app/const.go, src/core/model/types.go, src/core/provision/machine.go, src/core/provision/provisioner.go, src/core/provision/types.go, src/core/service/cluster.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/scripts/addons/nfs/class_v4.0.16.yaml, src/scripts/addons/nfs/deploy_v4.0.16.sh, src/scripts/addons/nfs/rbac_v4.0.16.yaml, src/scripts/bootstrap.sh
- feat: Add support for storageclass NFS
- NFS와 Ceph Rbd 지원 목표로 진행
- 외부 접속 가능한 NFS, Ceph cluster 사전 제공 전제
- NFS 
- 외부 nfs-subdir-external-provisioner 사용
- 클러스터 생성시 파라미터 추가
`"storageClass" : {
"nfs" : {
"server" : "123.456.789.123",
"path" : "/kube/data"
}
}`
- Ceph
- provisioner 4종 검토 : kubernetes.io/rbd, ceph.com/rbd,  rbd.csi.ceph.com,  Rook/ceph-external-cluster 
- kubernetes.io/rbd
- k8s 1.6부터 내장 rbd provieioner 가 지원되지 않으므로 사용 불가.
- ceph.com/rbd
- k8s 1.20 부터 SelfLink 가 사용중단 되었기 때문에 해당 오류로 인해 사용 불가.
-  rbd.csi.ceph.com
- pvc pending, pv 생성 실패. 실제 서버 경로에 접근이 안되는 것으로 보여짐.
-  Rook/ceph-external-cluster 
- 외부 cephcluster가 정상적으로 연결되지 않음.
- 번외로 rook-ceph 으로 mcks 에 ceph cluster를 설치 후 테스트 했지만 osd 생성 후 접근 불가.
**MCKS 환경에서 ceph 지원이 불가할 것으로 판단**
**Tested with**
- CB-Spider …
=> feat: Add support for storageclass nfs

src/core/service/csp.go
- fix:Add GuestOs to openstack image search condition
- openstack 버전만 다른 환경에서 기존 항목에 다른 값이 들어오는 현상으로 인해 추가.
**Tested with**
- CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.6.4)
- CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/releases/tag/v0.6.0)
=> fix:Add GuestOs to openstack image search condition

docs/design/entity.md, docs/test/cluster-create.sh, docs/test/mcir-delete.sh, docs/test/mcir-list.sh, src/core/app/ack.go, src/core/app/const.go, src/core/model/types.go, src/core/provision/provisioner.go, src/core/service/cluster.go, src/core/service/csp.go, src/core/service/mcir.go, src/core/tumblebug/mcir.go, src/core/tumblebug/types.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/scripts/k8s-init.sh
- feat: Add support for loadbalancer NLB
- nlb 방식 추가
- cluster 생성시  parameter 추가
ex) loadbalancer : nlb  (default: haproxy)
- ibm, cloudit 은 미지원 (추후 지원 예정)
- ibm : nlb 생성시 10분 이상 시간 소요됨, worker node join 이 안되는 현상 (확인 필요)
- cloudit : 클러스터 삭제시 nlb 를 먼저 삭제 해야 함. 로직 변경 필요. 
- aws, gcp, tencent, alibaba, openstack, azure 1차 지원
Tested with
CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.6.8)
CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug 최신소스)
=> feat:Add support for loadbalancer NLB

docs/test/cluster-create.sh, docs/test/node-add.sh, src/core/app/const.go, src/core/service/cluster.go, src/core/service/mcir.go, src/core/service/node.go, src/core/tumblebug/types.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml
- Add RootDiskType & RootDiskSize parameters 
- 클러스터 생성시 controlplane, worker 단위로만 가능함
- 기본 값인 default, default 로 값이 제대로 전달 되는 지 테스트 함
Tested with
CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.6.8)
CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/tag/v0.6.2)
=> feat:Add RootDiskType & RootDiskSize param to Create Cluster

src/core/provision/machine.go
* bootstrap.sh 실행 결과  체크 시 런타임 환경에 따라 output에 포함 안될 수 있는 문자열 확인하고 오류로 처리하는 부분 제거
=> fix: boostrap.sh output check

src/core/model/cluster.go, src/core/provision/machine.go, src/core/provision/provisioner.go, src/scripts/bootstrap.sh
* MCIS에서 vm default 계정이 공백일 경우 default 계정 (cb-user) 지정
* SSH handshake logs 세분화
* boostrap.sh permission error log  hidden 처리
* datastore 가 비어있을 경우 bucket not 오류와 exist 오류 구분 처리
* Tested with
* CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.6.8)
* CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/tag/v0.6.3)
=> fix: VM default account & ssh handshake logs

docs/design/entity.md, src/core/app/const.go, src/core/model/types.go, src/core/provision/machine.go, src/core/provision/provisioner.go, src/core/service/cluster.go, src/core/service/mcir.go, src/core/tumblebug/mcis.go, src/core/tumblebug/types.go, src/docs/docs.go, src/docs/swagger.json, src/docs/swagger.yaml, src/rest-api/router/cluster.go, src/scripts/bootstrap.sh, src/scripts/etcd-ca.sh, src/scripts/etcd-conf.sh, src/scripts/k8s-init-etcd.sh
- Add external etcd cluster
- external etcd 구성 시 control-plane 은 3,5,7 개로 제약함.
- 설치 후 control-plane 리더 접속 후 아래와 같이 etcd cluster 확인 가능
- $export ETCDCTL_API=3 
- $export ETCDCTL_ENDPOINTS=https://192.168.36.5:2379,https://192.168.36.6:2379,https://192.168.36.7:2379
- $export ETCDCTL_CACERT=/etc/kubernetes/pki/etcd/ca.pem
- $export ETCDCTL_CERT=/etc/kubernetes/pki/etcd/etcd.pem 
- $export ETCDCTL_KEY=/etc/kubernetes/pki/etcd/etcd-key.pem
- $etcdctl member list -w table
- $etcdctl endpoint status -w table
- $etcdctl endpoint health -w table
Tested with
CB-Spider (https://github.com/cloud-barista/cb-spider/releases/tag/v0.6.8)
CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug/tag/v0.6.3)
=> feat:Add external etcd cluster

src/core/service/cluster.go, src/core/service/mcir.go, src/core/tumblebug/mcir.go
- NCPVPC 사용시 loadbalancer type nlb 지원 추가
- mcks에서 nlb 사용을 위해서는 SGN(싱가포르), JPN(일본) 리전 사용해야함. 
Tested with
CB-Spider (https://github.com/cloud-barista/cb-spider) v0.7.0
CB-Tumblebug (https://github.com/cloud-barista/cb-tumblebug) v0.7.0
=> feat : Support to ncpvcp nlb
